/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GlBackgroundVideo {
    'muted': boolean;
    'poster': string;
    'src': string;
  }
  interface GlBackgroundVideoAttributes extends StencilHTMLAttributes {
    'muted'?: boolean;
    'poster'?: string;
    'src'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GlBackgroundVideo': Components.GlBackgroundVideo;
  }

  interface StencilIntrinsicElements {
    'gl-background-video': Components.GlBackgroundVideoAttributes;
  }


  interface HTMLGlBackgroundVideoElement extends Components.GlBackgroundVideo, HTMLStencilElement {}
  var HTMLGlBackgroundVideoElement: {
    prototype: HTMLGlBackgroundVideoElement;
    new (): HTMLGlBackgroundVideoElement;
  };

  interface HTMLElementTagNameMap {
    'gl-background-video': HTMLGlBackgroundVideoElement
  }

  interface ElementTagNameMap {
    'gl-background-video': HTMLGlBackgroundVideoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
